export const ANALYSIS_PLAYLISTS_SORT_REMEMBER = 'ANALYSIS_PLAYLISTS_SORT_REMEMBER';
export const ANALYSIS_PLAYLISTS_SORT_ACTIVE = 'ANALYSIS_PLAYLISTS_SORT_ACTIVE';
export const ANALYSIS_PLAYLISTS_SORT_DIRECTION = 'ANALYSIS_PLAYLISTS_SORT_DIRECTION';
